# Generated by Django 6.0.3 on 2026-05-03 18:59
import builtins
from django.db import migrations, models
class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_alter_categoria_options_alter_categoria_descricao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='origem',
            field=models.TextField(default='', verbose_name=builtins.max),
            preserve_default=False,
        ),
    ]
