# Generated by Django 6.0.3 on 2026-05-03 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0003_categoria_origem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='origem',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
