# Generated by Django 6.0.3 on 2026-05-21 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0005_dados_iniciais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.URLField(blank=True, null=True, verbose_name='URL da Imagem (Cloudinary)'),
        ),
    ]
